### ISSUE TITLE
Отчёт об ошибке

### ISSUE THREAD

**Issue by wenzyx** [FrameMuse/bug-free-octo-tribble#2]
*Ненужные поля удалить*

### Опишите баг
Опишите баг в двух словах.

- Это произошло на странице: ...
- Я был авторизован на сайте: Да 

### Компьютер (заполните поля ниже):
 - Браузер chrome
 - Версия [Например 22]

### Телефон (заполните поля ниже):
 - Устройство: [НапримерiPhone6]
 - Браузер [Например stock browser, safari]
 - Версия [Например 22]

### Доп. инфа
Можно рассказать об остальных проблемах в жизни

### Прикреплённый файл с ошибками:
{
  "error": {
    "message": "React Component Info [e.replaceAll is not a function]",
    "stack": [
      "",
      "at ContractCreatePanel (https://standoffcase.net/static/js/3.281d7aeb.chunk.js:1:183798)",
      "at ContractSwitchContent (https://standoffcase.net/static/js/3.281d7aeb.chunk.js:1:185870)",
      "at div",
      "at BranchSection (https://standoffcase.net/static/js/3.281d7aeb.chunk.js:1:2080)",
      "at div",
      "at Branch (https://standoffcase.net/static/js/3.281d7aeb.chunk.js:1:1590)",
      "at Contract (https://standoffcase.net/static/js/3.281d7aeb.chunk.js:1:186665)",
      "at RouterComponent (https://standoffcase.net/static/js/3.281d7aeb.chunk.js:1:241723)",
      "at Route (https://standoffcase.net/static/js/4.97185834.chunk.js:2:7250)",
      "at Switch (https://standoffcase.net/static/js/4.97185834.chunk.js:2:8297)",
      "at Router (https://standoffcase.net/static/js/3.281d7aeb.chunk.js:1:242323)",
      "at main",
      "at Suspense",
      "at StandoffCase",
      "at Router (https://standoffcase.net/static/js/4.97185834.chunk.js:2:5510)",
      "at Provider (https://standoffcase.net/static/js/4.97185834.chunk.js:2:30270)",
      "at Preload (https://standoffcase.net/static/js/main.a78c036e.chunk.js:1:556598)",
      "at ClientContextProvider (https://standoffcase.net/static/js/4.97185834.chunk.js:2:63113)",
      "at App (https://standoffcase.net/static/js/main.a78c036e.chunk.js:1:568999)"
    ]
  }
}

**Comment by FrameMuse** [comment]
Заменил "replaceAll" на "replace"
